version: '3.7' 
services: 
  flask-app:
    build: .
    container_name: flask-app
    ports:
     - "6000:5000"
    networks:
     - mynet
    depends_on:
     - es
    hostname: app
  es:
    platform: "linux/amd64"
    image: elasticsearch:6.8.23
    container_name: es
    ports:
     - "9200:9200"
    networks:
      - mynet
  nginx:
    platform: "linux/amd64"
    image: nginx:latest
    ports:
      - 80:80
    volumes:
     - ./ngnix/nginx.conf:/etc/nginx/
     - ./static:/usr/share/nginx/html/static
     - ./templates:/usr/share/nginx/html/templates
    networks:
      - mynet

networks:
  mynet:
    name: mynet

    